namespace Pinion.Engine.Reporting;

/// <summary>
/// Version of the generated characterization-test / golden-master format. Every generated test is stamped
/// with it (<c>// pinion-format: N</c>), so a future format change is DETECTABLE rather than silently
/// producing churn or false "behavior changed" diffs in users' committed suites.
/// <para>
/// Bump <see cref="Version"/> ONLY when the emitted test/snapshot shape changes in a way that isn't
/// backward-compatible with existing golden masters. <c>verify</c> reads the stamp and warns if a suite was
/// generated by a NEWER Pinion than the running build understands (so the user updates the tool instead of
/// chasing phantom behavior changes).
/// </para>
/// </summary>
public static class CharacterizationFormat
{
    /// <summary>Current generated-test/snapshot format version. Bump only on a breaking format change.</summary>
    public const int Version = 1;

    /// <summary>The comment prefix that carries the stamp at the top of a generated test.</summary>
    public const string StampPrefix = "// pinion-format:";

    /// <summary>The stamp line to emit as the first line of a generated test.</summary>
    public static string Stamp => $"{StampPrefix} {Version}";

    /// <summary>The format version stamped in a generated test's source, or null if unstamped (a
    /// pre-versioning suite — treat as legacy / format 0).</summary>
    public static int? ReadStamp(string source)
    {
        foreach (var line in source.Split('\n'))
        {
            string t = line.Trim();
            if (t.StartsWith(StampPrefix, System.StringComparison.Ordinal)
                && int.TryParse(t[StampPrefix.Length..].Trim(), out int v))
                return v;
        }
        return null;
    }
}
